

##################################################
## Alarm Panel Component
##################################################
alarm_control_panel:
  - platform: manual
  
##################################################
## Sensors
##################################################



##################################################
## Scripts
##################################################

##################################################
## Automation
##################################################