#File I use to test out components before adding them to my organization system


variable:
  private_ip:
    restore: true
    attributes:
      friendly_name: 'Private IP Variable'

sensor:
  - platform: imap_email_content
    server: imap.gmail.com
    port: 993
    username: !secret primary_email
    password: !secret gmusic_pass
    senders:
      - service@viarail.ca
      - kristianfjonesis@gmail.com


#automation:
#  - alias: "Private IP Change"
#    trigger:
      

