
##################################################
## Customize
##################################################
homeassistant:
  customize_glob:
    group.system_info_badges:
      state_card_mode: badges

##################################################
## Groups
##################################################
group:
  system_info:
    name: System
    entities:
      - group.system_info_badges
      - sensor.ipv4_address_eth0
      - sensor.version
      - input_select.ha_mode
  system_info_badges:
    entities:
      - sensor.processor_use
      - sensor.disk_free_
      - sensor.memory_free

##################################################
## Configuration
##################################################
#hassio:

##################################################
## Recorder
##################################################
recorder:
  purge_interval: 3
  purge_keep_days: 10

##################################################
## Logbook
##################################################
logbook:
  include:
#    entities:
#      - switch.
    domains:
      - alarm_control_panel
      - alert
      - light
      - sensor
      - binary_sensor
      - device_tracker
      - zwave

  exclude:
    entities:
       - sensor.since_last_boot
       - sensor.dark_sky_summary
#      - sensor.time
#      - sensor.date

##################################################
## History
##################################################
#https://home-assistant.io/components/history/
history:
  use_include_order: True
  include:
#    entities:
#      - switch.heater
    domains:
      - alarm_control_panel
      - alert
      - light
      - sensor
      - binary_sensor
      - device_tracker
      - zwave

#  exclude:
#    entities:
#      - sensor.time
#      - sensor.date

##################################################
## Sensors
##################################################
sensor:
  - platform: scrape
    resource: https://home-assistant.io
    select: ".current-version h1"

    #https://home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_free
      - type: ipv4_address
        arg: eth0
      - type: disk_free
        arg: /
      - type: since_last_boot

    #https://home-assistant.io/components/sensor.version/
  - platform: version
    name: version

  - platform: fastdotcom
    minute:
      - 0
      - 15
      - 30
      - 45

##################################################
## Scripts
##################################################



##################################################
## Automation
##################################################
automation:
  - alias: 'Home Assistant: Shutdown'
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      - service: script.ha_mode_set_normal

  - alias: 'Home Assistant: Startup'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: script.ha_mode_set_normal
      - service: group.set_visibility
        data:
          entity_id: group.maintenance_git_panel
          visible: no
#      - service: script.ha_startup

  - alias: 'Update Available Notifications'
    hide_entity: True
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      - service: script.notify_update
