#System Security Module

##################################################
## General
##################################################



##################################################
## Customize
##################################################


##################################################
## Groups
##################################################

##################################################
## Devices
##################################################

#
# Power cut detection, security panel
#
#

##################################################
## Alarm Control Panel
##################################################
## https://home-assistant.io/components/alarm_control_panel.manual/


  
##################################################
## Sensors
##################################################
sensor:
  - platform: haveibeenpwned
    email: !secret primary_email





##################################################
## Automation
##################################################


##################################################
## Scripts
##################################################
